#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define TRAIN_SIZE_FUDGE_FACTOR 100000
#define PICKUP_LENGTH_UM 50000
#define PICKUP_FRONT_TO_TRAIN_FRONT_UM 23000
#define PICKUP_BACK_TO_TRAIN_BACK_UM 141000
#define TRAIN_LENGTH_UM PICKUP_LENGTH_UM + PICKUP_FRONT_TO_TRAIN_FRONT_UM + PICKUP_BACK_TO_TRAIN_BACK_UM

#endif
